name: TIMBERPRO
favicon: null
layout_spectrum: 0.99519
typography_spectrum: 0.75489
title: TIMBERPRO News and Views
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7b7a7a'
    - '#018901'
    - '#ffffff'
    - '#80ff80'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
