name: TIMBERPRO
favicon: null
layout_spectrum: 0.7675546237733215
typography_spectrum: 0.603168259607628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8420753991231322
  lightness: 0.34130073664709926
  saturation: 0.6879112394526601
  rhythmicContrast: 0.03207973390817642
purpose: []
